microraiden/README.md
microraiden/microraiden/click_helpers.py
microraiden/microraiden/client/client.py
microraiden/microraiden/close_all_channels.py
microraiden/microraiden/examples/echo_client.py
microraiden/microraiden/examples/m2m_client.py
microraiden/microraiden/utils.py

Support JSON private keys.
Old format (raw hex encoded) is still supported, but will generate a warning, and should be considered deprecated in the future, as it's less secure and not standardized.
It will **interactively** ask for the password for decryption of the private key.
Optionally, CLI tools now have an option to pass the path of a file containing the password, for non-interactive opening of the private key (`docker` environments, scripting): `--private-key-password-file` for the proxy, `--key-password-path` for python Client/m2m.
Fix #100 .

Support JSON-encoded private keys, as generated by geth/parity

---

microraiden/microraiden/channel_manager.py
microraiden/microraiden/client/client.py
microraiden/microraiden/config.py
microraiden/microraiden/make_helpers.py
microraiden/microraiden/proxy/resources/expensive.py
microraiden/microraiden/test/config.py
microraiden/microraiden/test/fixtures/client.py
microraiden/microraiden/test/fixtures/web3.py
microraiden/microraiden/test/test_client.py

The address of the token contract doesn't have to be configured, as it's stored in the channel manager contract.

Use token contract address from channel manager

---

contracts/contracts/RaidenMicroTransferChannels.sol
contracts/contracts/Token/Token.sol

Still leaves one warning though.
```
contracts/contracts/RaidenMicroTransferChannels.sol:167:26: Warning: Function declared as view, but this expression (potentially) modifies the state and thus requires non-payable (the default) or payable.                                                                    
address signer = ECVerify.ecverify(prefixed_message_hash, _balance_msg_sig);                                                                                                                                                                                            
^--------------------------------------------------------^
```
We can't mark the ECRecover lib as pure due to it's assembly code doing a `CALL` into what is I assume the ecrecover precompiled contract, but the solidity …

Solc 0.4.17 fixes

---

contracts/contracts/RaidenMicroTransferChannels.sol
contracts/tests/fixtures.py
contracts/tests/test_raidenchannels.py

closes #99 
- string variable for compatibility with semantic versioning
- setter & getter for latest contract version Ethereum address
- setter only callable by owner
- unit test

Add versioning to the RaidenMicroTransferChannels contract

---

contracts/contracts/RaidenMicroTransferChannels.sol

`uint8` -> `max 2**8 * ~15sec / 60 = 64 min`
`uint16` -> `max 2**16 * 15 / 60 = 16384 min = 273h = 11.37 days`
`uint32` -> `max 2**16 * 15 / 60 = 45654 days`
uint8 was too small. It was chosen for decreasing gas - which is actually debatable and should be tested (EVM works with 256). Even so, you may want larger values without modifying the code.
Challenge period is anyway set at deployment, so you can make it as small as you like.
Also, it's used like this: (note block number type)
```
closing_requests[key].settle_block_number = uint32(block.number) + challenge_period;
```

Increase challenge_period type size from uint8 to uint32

---

contracts/contracts/RaidenMicroTransferChannels.sol

We do not need `_ deposit` in `ChannelToppedUp` event. We already have `_added_deposit`.
This saves gas.

Contract - remove deposit from ChannelToppedUp & save gas

---

contracts/contracts/RaidenMicroTransferChannels.sol

Channel data is already visible with `getChannelInfo` anyway.
Mentioned in https://github.com/raiden-network/microraiden/issues/134#issuecomment-347144899

Explicit visibility and code style fixes

---

contracts/contracts/RaidenMicroTransferChannels.sol
contracts/tests/test_channel_close.py
contracts/tests/test_ecverify.py
contracts/tests/utils.py

Fixes https://github.com/raiden-network/microraiden/issues/193
Discovered in https://github.com/raiden-network/microraiden/issues/134#issuecomment-347144899
- Include contract address in `_balance_msg_sig`
- Include contract & sender info in `_closing_sig` by just signing `keccak256(_balance_msg_sig)`
- Remove redundant signature length checks. This is done in `ECVerify.ecverify`.

Fix signature logic - prevent replay attack issue

---

contracts/contracts/MicroRaidenEIP712Helper.sol
contracts/contracts/RaidenMicroTransferChannels.sol
contracts/contracts/URaidenEIP712HelperContract.sol
contracts/tests/fixtures_uraiden.py
contracts/tests/test_channel_close.py
contracts/tests/test_channel_create.py
contracts/tests/test_channel_topup.py
contracts/tests/test_ecverify.py
contracts/tests/test_eip712.py
contracts/tests/test_uraiden.py

merge after https://github.com/raiden-network/microraiden/pull/198
fixes https://github.com/raiden-network/microraiden/issues/181 - you can change the balance proof message hash logic at any point.
EIP712 is not standardized and can have breaking changes.
- adds a setter in the uRaiden contract for setting the `URaidenEIP712HelperContract` address, callable only by the `RaidenMicroTransferChannels` contract owner
- exposes `getMessageHash` as a `pure` function, used in the uRaiden `verifyBalanceProof` function

Extract balance message hash logic for EIP712 in a separate contract

---

contracts/contracts/RaidenMicroTransferChannels.sol
contracts/tests/fixtures.py
contracts/tests/fixtures_uraiden.py
contracts/tests/test_channel_create.py
contracts/tests/test_channel_topup.py

mentioned in https://github.com/raiden-network/microraiden/issues/134
`tokenFallback` converts `uint256` to `uint192`, we want to make sure transaction fails if there is an overflow.

Contract - add check for uint conversion

---

contracts/contracts/RaidenMicroTransferChannels.sol
contracts/tests/fixtures.py
contracts/tests/test_channel_create.py
contracts/tests/test_channel_topup.py
contracts/tests/test_uraiden.py

Limit token deposits for the bug bounty Mainnet release.
Thought about taking token.decimals() into consideration, but decided to go with the simple solution. This function is not a requirement for erc20. Additionally, the scope is to preventively limit loss - hard to calculate for other tokens.

Add temporary bug bounty release channel deposit limit

---

microraiden/microraiden/client/default_http_client.py

If the client is out of sync with the server and receives payment headers with `Rdn-Invalid-Amount` set, it should retry the request with an updated balance.

Allow retry on invalid amount

---

microraiden/microraiden/client/client.py

The argument name for a top up event `_deposit` changed to `_added_deposit`.

Fix topup event argument names

---

microraiden/microraiden/channel_manager/manager.py
microraiden/microraiden/config.py
microraiden/microraiden/exceptions.py
microraiden/microraiden/test/test_version.py

The version check is done in the ChannelManager class and will
raise InvalidContractVersion exception on failed check.
Right now only a dumb comparison is done - in future minor version
changes of the contract will probably be backward-compatible.
Fixes #214

Add contract version check

---

microraiden/microraiden/channel_manager/__init__.py
microraiden/microraiden/channel_manager/blockchain.py
microraiden/microraiden/channel_manager/channel.py
microraiden/microraiden/channel_manager/manager.py
microraiden/microraiden/channel_manager/state.py
microraiden/microraiden/config.py
microraiden/microraiden/contract_proxy.py
microraiden/microraiden/proxy/paywalled_proxy.py
microraiden/microraiden/proxy/resources/expensive.py
microraiden/microraiden/test/fixtures/http_client.py
microraiden/microraiden/test/test_broke_proxy.py
microraiden/microraiden/test/test_channel_manager_db.py

If channel manager ether balance is too low, it can't dispute unhonest channel closes. This fix will add recover scenario for such situation.
In short, if channel can't be closed, its state will become `CLOSE_PENDING` and channel manager will attempt to close it again as soon as its ether balance is above the set limit.
Fixes #238

Handle case where channel manager has no eth left

---

contracts/contracts/RaidenMicroTransferChannels.sol

As reported in the bug bounty there is a potential (but quite unlikely
as this contract is not going to be here for that long and challenge
period is set to 500) for overflow if there is a very high challenge
period and if the block number is very high.
We add an assertion for such a scenario

Add overflow check for challenge period

---

microraiden/microraiden/examples/eth_ticker.py
microraiden/microraiden/test/test_eth_ticker.py

The ETH ticker test now mocks the bitfinex API call and allows for faster polling times.
The test might in some cases be too short for the ticker window to appear. It should at most take 2 seconds.

Faster ETH ticker test

---

microraiden/microraiden/proxy/resources/paywall_decorator.py
microraiden/microraiden/test/test_accept_html.py

Proxy should return `text/json` content type by default, and return `text/html` only if client requests it.

Fix Conent-Type - default is JSON

---

microraiden/microraiden/proxy/resources/paywall_decorator.py
microraiden/microraiden/test/test_proxy.py

This came up in a µRaiden application: When the returned resource had an explicit content type (for example `application/json` from a `jsonify()` call) the respective header wasn't merged properly but simply extended. This resulted in headers like `'Content-Type': 'application/json,application/json'` or `'Content-Type': 'application/json,text'`.
In this PR, header fields returned by the resource take precedence over default headers. That includes possibly overriding `RDN-...` fields. Not sure one would want that but just note that it's possible now.

Bug fix: proxy resource headers take precedence over default headers

---

microraiden/microraiden/requests/__init__.py
microraiden/microraiden/test/test_utils.py
microraiden/microraiden/utils/__init__.py
microraiden/microraiden/utils/misc.py

I noticed I might have to reuse the `kwarg` popping magic in the `microraiden.requests` module somewhere else, and @pcppcp mentioned he might need it in some places too, so here's a tiny PR pulling that functionality out into a module, covered by tests.

Requests kwarg popping moved to utility module

---

contracts/contracts/RaidenMicroTransferChannels.sol
contracts/tests/fixtures.py
contracts/tests/fixtures_uraiden.py
contracts/tests/test_channel_close.py
contracts/tests/test_channel_create.py
contracts/tests/test_channel_topup.py
contracts/tests/test_ecverify.py
contracts/tests/test_uraiden.py
contracts/tests/utils.py

fixes https://github.com/raiden-network/microraiden/issues/266
Open to suggestions for the `message_id` values.
As suggested in https://github.com/raiden-network/microraiden/issues/134#issuecomment-347144899
tl;dr
```python
bytes32 message_hash = keccak256(
keccak256(
'string message_id',
'address receiver',
'uint32 block_created',
'uint192 balance',
'address contract'
),
keccak256(
'Sender balance proof signature',
_receiver_address,
_open_block_number,
_balance,
address(this)
)
);
bytes32 message_hash = keccak256(
keccak256(
'string message_id',
'address sender',
'uint32 block_created',
'uint192 balance',
'address contract'
),
keccak256(
'Receiver closing signature',
_sender_address,
_open_block_number,
_balance,
address(this)
)
);
function cooperativeClose(
address _receiver_address, …
```

Contract closing signature

---

contracts/tests/fixtures.py
contracts/tests/fixtures_uraiden.py
contracts/tests/test_channel_create.py
contracts/tests/test_uraiden.py

To be reviewed after https://github.com/raiden-network/microraiden/pull/273 is merged.
- move create channel tests from the `get_channel` fixture used in all tests to dedicated tests
- shortens travis time relative to the above PR

Contract tests refactor open

---

contracts/contracts/RaidenMicroTransferChannels.sol
contracts/contracts/test/Delegate.sol
contracts/tests/fixtures.py
contracts/tests/fixtures_uraiden.py
contracts/tests/test_channel_close.py
contracts/tests/test_channel_create.py
contracts/tests/test_channel_delegate.py
contracts/tests/test_channel_topup.py
contracts/tests/test_ecverify.py
contracts/tests/test_trusted_contracts.py
contracts/tests/test_uraiden.py

closes https://github.com/raiden-network/microraiden/issues/147
- `trusted_contracts` array - passed as a contract constructor argument.
- add `addTrustedContracts` only callable by `owner_address`
- gas used for adding 1 trusted contract: `46888`
- gas used for adding 3 trusted contracts: `97644`
- add `removeTrustedContracts` only callable by `owner_address`
- gas used for adding 1 trusted contract: `16232`
- gas used for adding 3 trusted contracts: `20964`
- add event `TrustedContract(address indexed _trusted_contract_address, bool _trusted_status)`
- a trusted contract can send tokens and open & top up channels in behalf of a `sender` (support for both ERC20 & ERC223 contracts)
- `_data` argument from `tokenFallback` now has to contain:
```py
sender_address (20 bytes) + …
```

Open/topUp by delegate (trusted) contracts

---

contracts/contracts/RaidenMicroTransferChannels.sol
contracts/tests/fixtures.py
contracts/tests/fixtures_uraiden.py
contracts/tests/test_channel_close.py
contracts/tests/test_channel_withdraw.py
contracts/tests/test_uraiden.py

closes https://github.com/raiden-network/microraiden/issues/248
- add `withdraw` function 
- estimated gas cost: `72525` first withdrawal, `42589` subsequent withdrawals
- add `ChannelWithdraw` event
- `getChannelInfo` now returns
```
return (
key,
channels[key].deposit,
closing_requests[key].settle_block_number,
closing_requests[key].closing_balance,
withdrawn_balances[key]
);
```
- added `_receiver_tokens` to `ChannelSettled`
```
event ChannelSettled(
address indexed _sender,
address indexed _receiver,
uint32 indexed _open_block_number,
uint192 _balance,
uint192 _receiver_tokens);
```
- tests

Allow receiver to withdraw tokens without closing channel

---

microraiden/README.md

Because there's some import magic to work around a bug in `requests` package, it's not possible to import version string directly from `setup.py` if dependencies are not installed.
This PR mentions the issue in the docs.
[ci skip]

Add info on using `pip install -e` to the docs

---

microraiden/requirements-dev.txt
microraiden/requirements.txt

fixes https://github.com/raiden-network/microraiden/issues/303
This was solved for `requirements.txt`, but not for `requirements-dev.txt` in  https://github.com/raiden-network/microraiden/pull/327
Version is strictly specified due to version dependency issues related to the `cytoolz` package.

Update ethereum-tester to eth-tester==0.1.0b5

---

.gitignore
microraiden/microraiden/channel_manager/blockchain.py
microraiden/microraiden/channel_manager/manager.py
microraiden/microraiden/click_helpers.py
microraiden/microraiden/client/client.py
microraiden/microraiden/client/session.py
microraiden/microraiden/close_all_channels.py
microraiden/microraiden/config.py
microraiden/microraiden/examples/echo_client.py
microraiden/microraiden/examples/echo_server.py
microraiden/microraiden/examples/eth_ticker.py
microraiden/microraiden/make_helpers.py
microraiden/microraiden/test/config.py
microraiden/microraiden/test/conftest.py
microraiden/microraiden/test/fixtures/accounts.py
microraiden/microraiden/test/fixtures/client.py
microraiden/microraiden/test/fixtures/session.py
microraiden/microraiden/test/fixtures/web3.py
microraiden/microraiden/test/test_broke_proxy.py
microraiden/microraiden/test/test_channel_manager.py
microraiden/microraiden/test/test_contract.py
microraiden/microraiden/test/test_crypto.py
microraiden/microraiden/test/test_session.py
microraiden/microraiden/test/test_sqlite_types.py
microraiden/microraiden/test/test_version.py
microraiden/microraiden/test/utils/client.py
microraiden/microraiden/utils/contract.py

This PR mainly introduces some compatibility changes and command line options to the test environment to properly run the tests on a real testnet (tested with Ropsten).
To run on the testnet:
* Start a testnet node on `localhost:8545`
* Pass `--no-tester` to `pytest`
* Pass `--faucet-private-key <key>` to `pytest` where `<key>` is either a hex-encoded private key or a path to a JSON file. This account will be used to fund transactions with ETH and testnet RDN tokens. Total transaction cost should be below 0.5 ETH. Remaining ETH and RDN will be returned to this address.
* If the faucet private key is a JSON file, make sure to pass `--faucet-password-path <path>` for a file containing the private key password.
* Optionally: Use a different tester private key generator seed with …

Tests can be run on Ropsten

---

.travis.yml
microraiden/microraiden/test/conftest.py
microraiden/microraiden/test/test_examples.py
microraiden/microraiden/test/test_sqlite_types.py

This currently covers tests that depend on xorg or testnet environment.
The big deposit test is skipped until we have separate test configurations for different networks.

Automatically skip some tests

---

microraiden/microraiden/click_helpers.py

`state_file_name` uses `channel_manager_address`. This failed when the channel manager address was not provided in the cli arguments

Fix state_file when no channel_manager_address is provided

---

microraiden/microraiden/channel_manager/blockchain.py
microraiden/microraiden/config.py
microraiden/microraiden/proxy/resources/management.py
microraiden/microraiden/test/test_rest_api.py
microraiden/microraiden/webui/js/main.js
microraiden/microraiden/webui/microraiden/docs/README.md
microraiden/microraiden/webui/microraiden/docs/classes/deferred.md
microraiden/microraiden/webui/microraiden/docs/classes/microraiden.md
microraiden/microraiden/webui/microraiden/docs/interfaces/microchannel.md
microraiden/microraiden/webui/microraiden/docs/interfaces/microchannelinfo.md
microraiden/microraiden/webui/microraiden/docs/interfaces/microproof.md
microraiden/microraiden/webui/microraiden/docs/interfaces/microtokeninfo.md
microraiden/microraiden/webui/microraiden/docs/interfaces/msgparam.md
microraiden/microraiden/webui/microraiden/src/index.ts

A configuration with channel manager address and block number it was
deployed in is now available in `config.py`.
The block number is also exported via `/stats` REST endpoint to use in
js client etc.

Start syncing events from a specific block number

---

microraiden/microraiden/channel_manager/blockchain.py
microraiden/microraiden/channel_manager/manager.py
microraiden/microraiden/click_helpers.py
microraiden/microraiden/client/client.py
microraiden/microraiden/client/context.py
microraiden/microraiden/close_all_channels.py
microraiden/microraiden/config.py
microraiden/microraiden/constants.py
microraiden/microraiden/examples/demo_proxy/__main__.py
microraiden/microraiden/examples/echo_server.py
microraiden/microraiden/make_helpers.py
microraiden/microraiden/proxy/paywalled_proxy.py
microraiden/microraiden/proxy/resources/paywall_decorator.py
microraiden/microraiden/proxy/resources/proxy_url.py
microraiden/microraiden/test/conftest.py
microraiden/microraiden/test/fixtures/accounts.py
microraiden/microraiden/test/fixtures/variables.py
microraiden/microraiden/test/fixtures/web3.py
microraiden/microraiden/test/test_broke_proxy.py
microraiden/microraiden/test/test_client.py
microraiden/microraiden/test/test_network_config.py
microraiden/microraiden/test/test_rest_api.py
microraiden/microraiden/utils/contract.py

This PR makes it possible to configure network-related variables.
These include
- channel manager address
- start sync block
- gas price
- gas limit
- pot_gas_limit
I've moved most of the stuff from `config.py` to `constants.py`, as these are generally things that don't need frequent changes. `config.py` now includes network configuration and exports a global: `NETWORK_CFG` 
Also fixes #354

Config gas price

---

microraiden/microraiden/client/client.py
microraiden/microraiden/examples/echo_server.py
microraiden/microraiden/examples/eth_ticker.py
microraiden/microraiden/examples/ticker_proxy.py
microraiden/microraiden/test/fixtures/variables.py
microraiden/microraiden/test/fixtures/web3.py

- fix use of default channel manager address in client
- eth ticker proxy example uses a common `click` template

Update eth ticker example

---

contracts/contracts/RaidenMicroTransferChannels.sol

Issue raised in https://github.com/raiden-network/microraiden/issues/392 (add `require(withdrawn_balances[key] < _balance);` check in `settleChannel`)
To be discussed if this is really necessary.
In case the balance that has already been withdrawn is bigger than the closing balance, `settleChannel` would still fail without this underflow check when trying to transfer tokens to the receiver:
https://github.com/raiden-network/microraiden/blob/01346c05ac42abb9e4534888a64e0ca82d7fe448/contracts/contracts/RaidenMicroTransferChannels.sol#L642
In case of underflow:
```
receiver_remaining_tokens > token_instance.call().balanceOf(uraiden_instance.address)
```
due to already withdrawn tokens -> transaction would fail anyway.

Add underflow check for failing faster.

---

microraiden/microraiden/proxy/resources/proxy_url.py

Paywalled proxy will present webui to the browser even if the content itself isn't a html page.
Fixes #395

Fix paywall url webui injection

---

.gitattributes

Thanks to the [new release](https://github.com/github/linguist/releases/tag/v6.0.0) of Linguist we [can now have](https://github.com/github/linguist/pull/3973) solidity syntax highlighting in Github.

Add Solidity language highlighting in Github

---

requirements.txt

This is just a hotfix until populus fixes eth-abi incompatibility.

Freeze eth-abi to make Travis tests run again

---

microraiden/config.py
microraiden/make_helpers.py

web3>=4.0 doesn't accept non-checksummed addr for some methods
Fixes #441

Add checksummed addrs to network defaults

---

requirements.txt

This will keep the used version of pycryptodome lower than 3.5.0, which encounters build failure (#455 ):
(https://github.com/Legrandin/pycryptodome/issues/142)
It will also make the non-pip setup routine with setuptools work (#438 ):
`python setup.py install`

Dependencies fix: pycryptodome 3.5.0 build failure; flask/setuptools bug

---

readthedocs.yml

This makes use of the beta functionality of the more advanced yaml-file based deployment configuration on http://readthedocs.io .
Particularly, this hopefully solves #438 by changing the default setuptools deployment to a pip installation.

Add ReadTheDocs deployment config
