microraiden/microraiden/examples/demo_proxy/__main__.py, microraiden/microraiden/examples/demo_proxy/fortunes.py, microraiden/microraiden/test/fixtures/accounts.py, microraiden/microraiden/test/fixtures/proxy.py, microraiden/microraiden/test/fixtures/variables.py
just trivial fixes so `make bandit` exits with success
[skip ci]
(Does this work also for PR?)
=> simple fixes to make bandit analyzer happy

microraiden/README.md
=> updated docs: Infura mentioned as an alternative to local ethereum node

.travis.yml, .travis/download_solc.sh
This enables contract tests in Travis.
=> travis: enable contract tests

microraiden/microraiden/webui/index.html, microraiden/microraiden/webui/js/main.js, microraiden/microraiden/webui/js/microraiden.js
Use jQuery's Deferred to gather token webUi parallely, fetch token decimals, and use it across webUI to show and prompt numbers/balances with correct number of digits. Fix #87
=> Implement decimals in webUI

microraiden/microraiden/channel_manager.py
Closes https://github.com/raiden-network/microraiden/issues/125
=> Fixed error message in channel manager

microraiden/microraiden/channel_manager.py, microraiden/microraiden/test/test_channel_manager.py
=> Fix mtime ctime

microraiden/microraiden/channel_manager.py
=> Drop filename and tmp filename from state file

contracts/contracts/RaidenMicroTransferChannels.sol
At deployment of the Raiden micro transfer channel check that the token
contract has code.
=> Check token address has code

contracts/contracts/RaidenMicroTransferChannels.sol
Make the braces closing style follow the consistent K&R style we use in Raiden.
=> Braces closing style

contracts/contracts/RaidenMicroTransferChannels.sol
=> Fix braces closing style for if-else

contracts/README.md, contracts/deploy/deploy_testnet.py, contracts/deploy/utils.py, contracts/requirements.txt, contracts/setup.cfg, contracts/utils/sign.py, contracts/utils/utils.py
- fix deployment after latest changes
- add flake8 & fix code style
=> Fix contract deployment

contracts/contracts/RaidenMicroTransferChannels.sol, contracts/tests/fixtures.py, contracts/tests/test_raidenchannels.py
As documented in https://github.com/raiden-network/microraiden/issues/134
- Better variable naming - contract
- Fix comments
- Rename `close` functions to `cooperativeClose` & `uncooperativeClose`
- Refactor `settleChannel`, remove `min()` and `max()`
- Add overflow check
- Replace `!= 0` with `>0` for uint, code style fix
=> Contract internal audit 1

microraiden/microraiden/proxy/paywalled_proxy.py, microraiden/microraiden/proxy/resources/__init__.py, microraiden/microraiden/proxy/resources/management.py, microraiden/microraiden/test/test_rest_api.py
=> REST endpoint for contract ABI

microraiden/microraiden/client/default_http_client.py, microraiden/microraiden/client/http_client.py, microraiden/microraiden/header.py, microraiden/microraiden/proxy/resources/expensive.py, microraiden/microraiden/test/fixtures/client.py, microraiden/microraiden/test/fixtures/http_client.py, microraiden/microraiden/test/test_http_client.py
This fixes a bug where it was possible to get the proxy resource
by signing a balance proof with a balance difference less than
requested amount.
Fixes #173 and #172
=> proxy underpay bugfix

contracts/contracts/RaidenMicroTransferChannels.sol
Ensure Checks-Effects-Interactions Pattern to avoid race conditions
Channel data has to be deleted in `settleChannel` before the token transfers.
I don't think there can be a race condition in `topUpPrivate`, but at least we fail faster topUpPrivate has a lot of checks.
=> Contract - transfer tokens after state change

microraiden/microraiden/channel_manager/blockchain.py, microraiden/microraiden/channel_manager/manager.py, microraiden/microraiden/channel_manager/state.py, microraiden/microraiden/test/fixtures/channel_manager.py, microraiden/microraiden/test/fixtures/variables.py, microraiden/microraiden/test/test_channel_manager.py, microraiden/microraiden/test/test_channel_manager_db.py
- added ':memory:' target for sqlite
- improved tests setup/teardown
=> sqlite update:

microraiden/microraiden/channel_manager/blockchain.py, microraiden/microraiden/channel_manager/state.py, microraiden/microraiden/client/client.py, microraiden/microraiden/config.py, microraiden/microraiden/make_helpers.py, microraiden/microraiden/test/conftest.py, microraiden/microraiden/test/fixtures/channel_manager.py, microraiden/microraiden/test/fixtures/variables.py, microraiden/microraiden/test/test_client.py, microraiden/microraiden/test/test_eth_ticker.py, microraiden/microraiden/test/test_http_client.py, microraiden/microraiden/test/test_performance.py
Token name is now specified in a single place - in the `config.py` file.
=> made contracts ABI parametrized

contracts/contracts/RaidenMicroTransferChannels.sol
Redundant
Mentioned in 
- https://github.com/raiden-network/microraiden/issues/134#issuecomment-347144899
- https://github.com/raiden-network/microraiden/issues/135
=> Remove isToken, prefix, token_address

microraiden/microraiden/channel_manager/blockchain.py, microraiden/microraiden/channel_manager/manager.py, microraiden/microraiden/client/channel.py, microraiden/microraiden/client/default_http_client.py, microraiden/microraiden/contract_proxy.py, microraiden/microraiden/crypto.py, microraiden/microraiden/data/contracts.json, microraiden/microraiden/proxy/resources/management.py, microraiden/microraiden/test/fixtures/client.py, microraiden/microraiden/test/fixtures/web3.py, microraiden/microraiden/test/test_channel_manager.py, microraiden/microraiden/test/test_client.py, microraiden/microraiden/test/test_crypto.py, microraiden/microraiden/test/test_http_client.py, microraiden/microraiden/test/utils/client.py
Synced with contract changes introduced in #198
=> Closing signature and balance proof replay protection (Python-side)

microraiden/microraiden/proxy/paywalled_proxy.py, microraiden/microraiden/proxy/resources/__init__.py, microraiden/microraiden/proxy/resources/management.py, microraiden/microraiden/test/test_rest_api.py
merged manager & token ABI to `/stats` REST endpoint
=> merged /stats REST endpoint

microraiden/microraiden/proxy/resources/expensive.py, microraiden/microraiden/test/fixtures/proxy.py, microraiden/microraiden/test/test_proxy.py
=> Fixes dynamic prices in paywall proxy

contracts/contracts/RaidenMicroTransferChannels.sol, contracts/tests/fixtures.py, contracts/tests/test_uraiden.py
As indicated in the external audit, point 7 https://github.com/raiden-network/microraiden/issues/135
=> Contract - require challenge_period >= 500

contracts/contracts/RaidenMicroTransferChannels.sol, contracts/tests/test_uraiden.py
Recommended in point 8 of the external audit: https://github.com/raiden-network/microraiden/issues/135
=> Contract - check constructor arg is a Token address

README.md, contracts/README.md, contracts/deploy/deploy_testnet.py
fixes https://github.com/raiden-network/microraiden/issues/41 also 
- fix deployment, contract addresses for kovan, quick proxy start
=> Update docs, deploy testnet

microraiden/microraiden/client/http_client.py, microraiden/microraiden/test/test_http_client.py, microraiden/microraiden/test/utils/client.py
=> added `on_http_response()` method to the http client

README.md
Closes https://github.com/raiden-network/microraiden/issues/237
=> Mention contract versioning in docs.

contracts/contracts/RaidenMicroTransferChannels.sol
fixes https://github.com/raiden-network/microraiden/issues/269
- use @notice for natspec docs
- fix order of functions after Solidity guidelines http://solidity.readthedocs.io/en/develop/style-guide.html#order-of-functions
=> Fix comments, add @notice, fix function order

microraiden/Makefile, microraiden/microraiden/config.py, microraiden/setup.cfg, microraiden/setup.py
=> Make uRaiden available on pypi

contracts/contracts/RaidenMicroTransferChannels.sol, contracts/tests/fixtures_uraiden.py
- code style & comment fixes
- changed argument names for all events
- `_sender` -> `_sender_address`
- `_receiver` -> `_receiver_address`
- use `view` instead of `constant`
=> Contract style

microraiden/microraiden/channel_manager/blockchain.py, microraiden/microraiden/client/channel.py, microraiden/microraiden/client/client.py, microraiden/microraiden/close_all_channels.py, microraiden/microraiden/config.py, microraiden/microraiden/data/contracts.json, microraiden/microraiden/test/fixtures/web3.py
fixes https://github.com/raiden-network/microraiden/issues/331
fixes https://github.com/raiden-network/microraiden/issues/329 
- update contract.json after contract changes
- update channel manager & python client after contract changes
- event arguments, getChannelInfo, ERC223 create channel & topup
=> Update contract.json, channel manager, python client

contracts/deploy/deploy_testnet.py
- replace outdated `web3.currentProvider`
- remove not needed code
=> Replace outdated web3.currentProvider

microraiden/microraiden/examples/echo_server.py, microraiden/microraiden/make_helpers.py
- non-checksummed channel manager address support
- private key is read from a file
=> Fix broken echo server

microraiden/microraiden/channel_manager/manager.py
=> Remove maintenance number from the version check

microraiden/.gitignore, microraiden/microraiden/config.py, microraiden/setup.cfg, microraiden/setup.py
Also bumped microraiden version.
=> Add npm compilation to `setup.py`

microraiden/microraiden/client/session.py, microraiden/microraiden/header.py, microraiden/microraiden/proxy/resources/paywall_decorator.py, microraiden/microraiden/proxy/resources/request_data.py, microraiden/microraiden/test/test_session.py
- remove deprecated `RDN-Insufficient-Funds` header
- replace with invalid proof header in the python client
- move header & cookies ValueError check after values are updated, to also catch invalid cookie values
=> Headers cleanup

microraiden/microraiden/click_helpers.py, microraiden/microraiden/close_all_channels.py, microraiden/microraiden/test/fixtures/client.py, microraiden/microraiden/test/test_client.py, microraiden/microraiden/test/test_close_all_channels.py, microraiden/microraiden/test/test_withdraw_tokens.py, microraiden/microraiden/withdraw_tokens.py
And fixes & improvements to close_all_channels.py script. Both tested in Ropsten, with live example, and working against current master. Fix #330
=> Withdraw script

microraiden/microraiden/examples/ticker_client.py, microraiden/microraiden/examples/ticker_proxy.py, microraiden/microraiden/test/test_examples.py
Eth ticker is now split to a proxy and client part.
=> Update eth ticker example.

README.md
Fixed two broken links in Quick-start
=> Fixed broken Links

docs/applications/pyclient/usage.rst, docs/introduction/introduction.rst
Some documents links for microraiden according to Olivers comments. The earlier PR #456  should be closed.
=> Internal document links for microraiden

microraiden/click_helpers.py
=> typo fixed
